### PR TITLE
MRG fixes for python 3 and new MNE

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by agramfort** [comment]
@mmoussallam from the good old days...

**Comment by mmoussallam** [comment]
@agramfort can't believe it was 8 years ago already ...

Thanks for the cleaning phase, let me know if I can help, and happy new year !

**Comment by agramfort** [comment]
yes time flies... I am just worried about the result I now obtain with demo_sample_denoising.py with S-BIRD

no idea what's going on but it seems wrong. If you have some time to look it would be great.

**Comment by mmoussallam** [comment]
I do get some decent results when running the code for S-birds-bird_sample

**Comment by mmoussallam** [comment]
However I'm not familiar with the new way to generate evoked potential in mne so I haven't checked that this is equivalent to what we had with a SNR of 9.

**Comment by mmoussallam** [comment]
Note that the default parameters in the script were not the same as the ones used for creating the figures in the paper.
If I use the same values (C=20 channels) I can reproduce the paper figures:
White noise:s-bird_sample20chans_white
Pink noise: s-bird_sample20chans

**Comment by agramfort** [comment]
can you push the fix to my PR?

>

**Comment by mmoussallam** [comment]
pushed, but it's not really a fix, just a parameter change :)

**Comment by agramfort** [comment]
now you force me to use notebooks...

https://docs.google.com/presentation/d/1n2RlMdmv1p25Xy5thJUhkKGvjtV-dkAIsUXP-AL4ffI/edit#slide=id.g362da58057_0_1

can you just push the diff on the python file?

**Comment by mmoussallam** [comment]
No time to go through the slides but it seems to contain a lot of memes so I bow ..

**Comment by agramfort** [comment]
running demo_sample_denoising.py gives

Screenshot 2021-01-04 at 14 45 48

do you see the same?

**Comment by mmoussallam** [comment]
I don't have a `demo_sample_denoising.py` script, only `demo_meg_denoising.py` and `demo_simu_denoising.py` and both are working

**Comment by agramfort** [comment]
arffff this script is not part of the repo... so I guess we are all good !

thanks @mmoussallam for the review and the help

**Comment by agramfort** [comment]
new release on pypi

https://pypi.org/project/bird/

>

**Pull request merged**
